// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbvpktatmpmnawottmwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJidnBrdGF0bXBtbmF3b3R0bXdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NjA3NzAsImV4cCI6MjA3MTUzNjc3MH0.qcCSRfC2h4kNaJg6kVGJFYaH392QqJrhiZ-O57F-kb8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});